name: Build PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux-deb:
    name: Linux build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            qt_arch: linux_gcc_64
          - arch: arm64
            runner: ubuntu-24.04-arm
            qt_arch: linux_gcc_arm64

    steps:
      - name: Build and test
        id: build
        uses: ./.github/actions/build-linux
        with:
          qt_arch: ${{ matrix.qt_arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qteasytier-pr-${{ github.event.pull_request.number }}-${{ matrix.arch }}
          path: build/Output
          if-no-files-found: error

  windows-zip:
    name: Windows build amd64
    runs-on: windows-2022

    env:
      BUILD_DIR: build
      MSYSTEM: UCRT64
      CHERE_INVOKING: 1

    steps:
      - name: Build and test
        id: build
        uses: ./.github/actions/build-windows

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qteasytier-pr-${{ github.event.pull_request.number }}-windows-amd64
          path: build/Output
          if-no-files-found: error
